
networks:
  tunneled:
  nextcloud-aio:
    external: true
  firefly_firefly_iii:
    external: true

services:

  cloudflared:
    container_name: cloudfered_tunnel
    image: cloudflare/cloudflared:1800-17533b124c22
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$CLOUD_FLARE_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - tunneled
      - nextcloud-aio
      - firefly_firefly_iii
